import { MarcaType } from '../types/types';

export const marca: MarcaType[] = [
  { label: 'Todos', value: 'Todos' },
  { label: 'Toto', value: 'Toto' },
  { label: 'Tokico', value: 'Tokico' },
  { label: 'Ndc', value: 'Ndc' },
  { label: 'Tahio', value: 'Tahio' },
  { label: 'Rik', value: 'Rik' },
  { label: 'Tp', value: 'Tp' },
  { label: 'Npr', value: 'Npr' },
  { label: 'Daido', value: 'Daido' },
  { label: 'INR', value: 'INR' },
  { label: 'Nok', value: 'Nok' },
  { label: 'Pos', value: 'Pos' },
  { label: 'Sideral', value: 'Sideral' },
  { label: 'Treefive', value: 'Treefive' },
  { label: '555', value: '555' },
  { label: 'THO', value: 'THO' },
  { label: 'Safety', value: 'Safety' },
  { label: 'Sabo', value: 'Sabo' },
  { label: 'FRACO', value: 'FRACO' },
  { label: 'Tamayo', value: 'Tamayo' },
  { label: 'TNK', value: 'TNK' },
  { label: 'Technorot', value: 'Technorot' },
  { label: 'Taiwan', value: 'Taiwan' },
  { label: 'Japon', value: 'Japon' },
  { label: 'Original', value: 'Original' },
  { label: 'Mobis', value: 'Mobis' },
  { label: 'Bwb', value: 'Bwb' },
  { label: 'Valeo', value: 'Valeo' },
  { label: 'Aubos', value: 'Aubos' },
  { label: 'Koyo', value: 'Koyo' },
  { label: 'Toyo', value: 'Toyo' },
  { label: 'Titan', value: 'Titan' },
  { label: 'Ichiban', value: 'Ichiban' },
  { label: 'NTN', value: 'NTN' },
  { label: 'KMX', value: 'KMX' },
  { label: 'Gabriel', value: 'Gabriel' },
  { label: 'Sonico', value: 'Sonico' },
  { label: 'Safety', value: 'Safety' },
  { label: 'Timken', value: 'Timken' },
  { label: 'Marfak', value: 'Marfak' },
  { label: 'Texamatic', value: 'Texamatic' },
  { label: 'Mobil', value: 'Mobil' },
  { label: 'Havoline', value: 'Havoline' },
  { label: 'Ac delco', value: 'Ac delco' },
  { label: 'Denso', value: 'Denso' },
  { label: 'Gap', value: 'Gap' },
  { label: 'Chuzent', value: 'Chuzent' },
  { label: 'Hc', value: 'Hc' },
  { label: 'Incolca', value: 'Incolca' },
  { label: 'Nacional', value: 'Nacional' },
  { label: 'Narva', value: 'Narva' },
  { label: 'Bosch', value: 'Bosch' },
  { label: 'Aisin', value: 'Aisin' },
  { label: 'Kiosan', value: 'Kiosan' },
  { label: 'Btk', value: 'Btk' },
  { label: 'Tkd', value: 'Tkd' },
  { label: 'Ysk', value: 'Ysk' },
  { label: 'Npc', value: 'Npc' },
  { label: 'Jaferpa', value: 'Jaferpa' },
  { label: 'Novex', value: 'Novex' },
  { label: 'Gamax', value: 'Gamax' },
  { label: 'Ekoline', value: 'Ekoline' },
  { label: 'Break pars', value: 'Break pars' },
  { label: 'Apc', value: 'Apc' },
  { label: 'Gauss', value: 'Gauss' },
  { label: 'Reanult', value: 'Reanult' },
  { label: 'Dreck', value: 'Dreck' },
  { label: 'Qap', value: 'Qap' },
  { label: 'Yec', value: 'Yec' },
  { label: 'KYB', value: 'KYB' },
  { label: 'TZK', value: 'TZK' },
  { label: 'Reik', value: 'Reik' },
  { label: 'Asco', value: 'Asco' },
  { label: 'Global Ram', value: 'Global Ram' },
  { label: 'Daico', value: 'Daico' },
  { label: 'Mitsuboshi', value: 'Mitsuboshi' },
  { label: 'NPC', value: 'NPC' },
  { label: 'Daikin', value: 'Daikin' },
  { label: 'Yomo', value: 'Yomo' },
  { label: 'Tomita', value: 'Tomita' },
  { label: 'Spicer', value: 'Spicer' },
  { label: 'CRC', value: 'CRC' },
  { label: 'CTR', value: 'CTR' },
  { label: 'Wanyuu', value: 'Wanyuu' },
  { label: 'DEPO', value: 'DEPO' },
  { label: 'Spirax', value: 'Spirax' },
  { label: 'MRK', value: 'MRK' },
  { label: 'NACHI', value: 'NACHI' },
  { label: 'UNIFAR', value: 'UNIFAR' },
  { label: 'Skd', value: 'Skd' },
  { label: 'EP', value: 'EP' },
  { label: 'Dokuro', value: 'Dokuro' },
  { label: '3BBB', value: '3BBB' },
  { label: 'LAGZ', value: 'LAGZ' },
  { label: 'ROCKY', value: 'ROCKY' },
  { label: 'BEN BRAND', value: 'BEN BRAND' },
  { label: 'TORICA', value: 'TORICA' },
  { label: 'BETO', value: 'BETO' },
  { label: 'Loctite', value: 'Loctite' },
  { label: 'Guayacol', value: 'Guayacol' },
  { label: 'Continental', value: 'Continental' },
  { label: 'Gates', value: 'Gates' },
  { label: 'Sun', value: 'Sun' },
  { label: 'Toyo', value: 'Toyo' },
  { label: 'NSK', value: 'NSK' },
  { label: 'Century', value: 'Century' },
  { label: 'Toba', value: 'Toba' },
  { label: 'Super', value: 'Super' },
  { label: 'Lucas', value: 'Lucas' },
  { label: 'SKB', value: 'SKB' },
  { label: 'Hastings', value: 'Hastings' },
  { label: 'MAHLE', value: 'MAHLE' },
  { label: 'SULOY', value: 'SULOY' },
  { label: 'Right Way', value: 'Right Way' },
  { label: 'OKAP', value: 'OKAP' },
  { label: 'DS', value: 'DS' },
  { label: 'ZTR', value: 'ZTR' },
  { label: 'FV', value: 'FV' },
  { label: 'MUSASHI', value: 'MUSASHI' },
  { label: 'VICTOR', value: 'VICTOR' },
  { label: 'Zuiko', value: 'Zuiko' },
  { label: 'Eiko', value: 'Eiko' },
  { label: 'Jozama', value: 'Jozama' },
  { label: 'Transejes', value: 'Transejes' },
  { label: 'Seiwa', value: 'Seiwa' },
  { label: 'AYG', value: 'AYG' },
  { label: 'New Pro', value: 'New Pro' },
  { label: 'Shimahide', value: 'Shimahide' },
  { label: 'JMB', value: 'JMB' },
  { label: 'Partcraft', value: 'Partcraft' },
  { label: 'Fic', value: 'Fic' },
  { label: 'Jaher', value: 'Jaher' },
  { label: 'Gsp', value: 'Gsp' },
  { label: 'GEN', value: 'GEN' },
  { label: 'Daewha', value: 'Daewha' },
  { label: 'OBC', value: 'OBC' },
  { label: 'Napco', value: 'Napco' },
  { label: 'EXP', value: 'EXP' },
  { label: 'Hibari', value: 'Hibari' },
  { label: 'DID', value: 'DID' },
  { label: 'VDC', value: 'VDC' },
  { label: 'WYR', value: 'WYR' },
  { label: 'Super kote', value: 'Super kote' },
  { label: 'Freshtone', value: 'Freshtone' },
  { label: 'Engine Master', value: 'Engine Master' },
  { label: 'Gti', value: 'Gti' },
  { label: 'TechnoGama', value: 'TechnoGama' },
  { label: 'Ads', value: 'Ads' },
  { label: 'Super3', value: 'Super3' },
  { label: 'Yokomitsu', value: 'Yokomitsu' },
  { label: 'Kapars', value: 'Kapars' },
  { label: 'Fritec', value: 'Fritec' },
  { label: 'Sanyco', value: 'Sanyco' },
  { label: 'Transtec', value: 'Transtec' },
  { label: 'Sam', value: 'Sam' },
  { label: 'AVM', value: 'AVM' },
  { label: 'Np', value: 'Np' },
  { label: 'Genuine pars', value: 'Genuine pars' },
  { label: 'Sintrametal', value: 'Sintrametal' },
  { label: 'TRW', value: 'TRW' },
  { label: 'DTC', value: 'DTC' },
  { label: 'IGO', value: 'IGO' },
  { label: 'Lyo', value: 'Lyo' },
  { label: 'TQW', value: 'TQW' },
  { label: 'Mp', value: 'Mp' },
  { label: 'Cometa', value: 'Cometa' },
  { label: 'Sime', value: 'Sime' },
  { label: 'DJB', value: 'DJB' },
  { label: 'Osteam', value: 'Osteam' },
  { label: 'Vernet', value: 'Vernet' },
  { label: 'ATC', value: 'ATC' },
  { label: 'Yadong', value: 'Yadong' },
  { label: 'SAFE', value: 'SAFE' },
  { label: 'Alta Max', value: 'Alta Max' },
  { label: 'Mando', value: 'Mando' },
  { label: 'Magneti Marelii', value: 'Magneti Marelii' },
  { label: 'DAYO', value: 'DAYO' },
  { label: 'Eiko', value: 'Eiko' },
  { label: 'Thomson', value: 'Thomson' },
  { label: 'FRS', value: 'FRS' },
  { label: 'SDK', value: 'SDK' },
  { label: 'LUK', value: 'LUK' },
  { label: 'NAVCAR', value: 'NAVCAR' },
  { label: 'Keyster', value: 'Keyster' },
  { label: 'Tonimo', value: 'Tonimo' },
  { label: 'Herko', value: 'Herko' },
  { label: 'Terpel', value: 'Terpel' },
  { label: 'COFRE', value: 'COFRE' },
  { label: 'TOP1', value: 'TOP1' },
  { label: 'PYSTA', value: 'PYSTA' },
  { label: 'ABRO', value: 'ABRO' },
  { label: 'OSK', value: 'OSK' },
  { label: 'JAFS', value: 'JAFS' },
  { label: 'Replascol', value: 'Replascol' },
  { label: 'AHS australina', value: 'AHS australina' },
  { label: 'JM', value: 'JM' },
  { label: 'AWD CHAIN', value: 'AWD CHAIN' },
  { label: 'DONGIN', value: 'DONGIN' },
  { label: 'ONNURI', value: 'ONNURI' },
  { label: 'Seco', value: 'Seco' },
  { label: 'Herlux', value: 'Herlux' },
  { label: 'RAP', value: 'RAP' },
  { label: 'NAMCCO', value: 'NAMCCO' },
  { label: 'SECO', value: 'SECO' },
  { label: 'Simoniz', value: 'Simoniz' },
  { label: 'NEW ERA', value: 'NEW ERA' },
  { label: 'Tech parts', value: 'Tech parts' },
  { label: 'Motoroke', value: 'Motoroke' },
  { label: 'INPARTS', value: 'INPARTS' },
  { label: 'Velko', value: 'Velko' },
  { label: 'EBI', value: 'EBI' },
  { label: 'WTB', value: 'WTB' },
  { label: 'NIPON PARTS', value: 'NIPON PARTS' },
  { label: 'KARSON', value: 'KARSON' },
  { label: 'BEARMACH', value: 'BEARMACH' },
  { label: 'OBC japon', value: 'OBC japon' },
  { label: 'Marh', value: 'Marh' },
  { label: 'GM', value: 'GM' },
  { label: 'ELGIN', value: 'ELGIN' },
  { label: 'TRC', value: 'TRC' },
  { label: 'United Parts', value: 'United Parts' },
  { label: 'Hasaki', value: 'Hasaki' },
  { label: 'Delphi', value: 'Delphi' },
  { label: 'Incolbest', value: 'Incolbest' },
  { label: 'FRASLE', value: 'FRASLE' },
  { label: 'MDS', value: 'MDS' },
  { label: 'SPS', value: 'SPS' },
  { label: 'OKAMI', value: 'OKAMI' },
  { label: 'DOLGIN', value: 'DOLGIN' },
  { label: 'JP', value: 'JP' },
  { label: 'Sambel', value: 'Sambel' },
  { label: 'Molpower', value: 'Molpower' },
  { label: 'FANAUTO', value: 'FANAUTO' },
  { label: 'Motocraft', value: 'Motocraft' },
  { label: 'NGK', value: 'NGK' },
  { label: 'Franig', value: 'Franig' },
  { label: 'Kehua', value: 'Kehua' },
  { label: 'Master', value: 'Master' },
  { label: 'TSK', value: 'TSK' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Filplus', value: 'Filplus' },
  { label: 'Guayas B&G', value: 'Guayas B&G' },
  { label: 'Eristic', value: 'Eristic' },
  { label: 'Isuzu', value: 'Isuzu' },
  { label: 'Mitsubishi', value: 'Mitsubishi' },
  { label: 'Toyota', value: 'Toyota' },
  { label: 'Mecoful', value: 'Mecoful' },
  { label: 'StarParts', value: 'StarParts' },
  { label: 'ATE', value: 'ATE' },
  { label: 'Talleres Diaz', value: 'Talleres Diaz' },
  { label: 'Ten 10', value: 'Ten 10' },
  { label: 'TY', value: 'TY' },
  { label: 'Ek', value: 'Ek' },
  { label: 'JOINFUJI', value: 'JOINFUJI' },
  { label: 'SANKEI', value: 'SANKEI' },
  { label: 'ART', value: 'ART' },
  { label: 'ROCKY', value: 'ROCKY' },
  { label: 'MITOYO', value: 'MITOYO' },
  { label: 'MOTECH TW', value: 'MOTECH TW' },
  { label: 'CIC', value: 'CIC' },
  { label: 'SHIN-ICHI', value: 'SHIN-ICHI' },
  { label: 'TH-NAC', value: 'TH-NAC' },
  { label: 'TOKOMITSU', value: 'TOKOMITSU' },
  { label: 'GMSGS', value: 'GMSGS' },
  { label: 'JPR', value: 'JPR' },
  { label: 'ROYAL', value: 'ROYAL' },
  { label: 'TOPLE', value: 'TOPLE' },
  { label: 'Sowa', value: 'Sowa' },
  { label: 'MITSUBARU', value: 'MITSUBARU' },
  { label: 'YWK', value: 'YWK' },
  { label: 'START PARTS', value: 'START PARTS' },
  { label: 'AZ', value: 'AZ' },
  { label: 'NDL', value: 'NDL' },
  { label: 'DAYO', value: 'DAYO' },
  { label: 'INDYMETAL', value: 'INDYMETAL' },
  { label: 'FLORIO', value: 'FLORIO' },
  { label: 'MACWAY', value: 'MACWAY' },
  { label: 'METALCAUCHO', value: 'METALCAUCHO' },
  { label: 'WC', value: 'WC' },
  { label: 'SRS', value: 'SRS' },
  { label: 'TEKNOROT', value: 'TEKNOROT' },
  { label: 'NAIW', value: 'NAIW' },
  { label: 'ASAM', value: 'ASAM' },
  { label: 'AUTOKIREN', value: 'AUTOKIREN' },
  { label: 'SOG', value: 'SOG' },
  { label: 'Novex LD', value: 'Novex LD' },
  { label: 'NOK JAPON', value: 'NOK JAPON' },
  { label: 'NOK SINGAPUR', value: 'NOK SINGAPUR' },
  { label: 'LUBRISTON', value: 'LUBRISTON' },
  { label: 'DREIK', value: 'DREIK' },
  { label: 'FBJ', value: 'FBJ' },
  { label: 'TRW', value: 'TRW' },
  { label: 'EXEDY', value: 'EXEDY' },
  { label: 'TIK', value: 'TIK' },
  { label: 'SI', value: 'SI' },
  { label: 'NVM', value: 'NVM' },
  { label: 'RBH', value: 'RBH' },
  { label: 'GMB', value: 'GMB' },
  { label: 'LYP', value: 'LYP' },
  { label: 'Aisan', value: 'Aisan' },
  { label: 'NPW', value: 'NPW' },
  { label: 'Kyosan', value: 'Kyosan' },
  { label: 'KOK', value: 'KOK' },
  { label: 'BGF', value: 'BGF' },
  { label: 'Transfer gear', value: 'Transfer gear' },
  { label: 'Wilson', value: 'Wilson' },
  { label: 'Brake pak', value: 'Brake pak' },
  { label: 'Jomo', value: 'Jomo' },
  { label: 'Chino', value: 'Chino' },
  { label: 'Koreano', value: 'Koreano' },
  { label: 'CAMSHAFT', value: 'CAMSHAFT' },
  { label: 'INSIDE', value: 'INSIDE' },
  { label: 'DONGIL', value: 'DONGIL' },
  { label: 'DAYCO', value: 'DAYCO' },
  { label: 'DFL', value: 'DFL' },
  { label: 'PC global', value: 'PC global' },
  { label: 'LUXE', value: 'LUXE' },
  { label: 'NIFASA', value: 'NIFASA' },
  { label: 'YAS', value: 'YAS' },
  { label: 'SKP', value: 'SKP' },
  { label: 'NISSEKI', value: 'NISSEKI' },
  { label: 'ADVICS', value: 'ADVICS' },
  { label: 'TRU-SPARK', value: 'TRU-SPARK' },
  { label: 'HANGHA', value: 'HANGHA' },
  { label: 'PRECISION MACHINED', value: 'PRECISION MACHINED' },
  { label: 'HIGHLINK', value: 'HIGHLINK' },
  { label: 'ENZO', value: 'ENZO' },
  { label: 'TUIJIANG TW', value: 'TUIJIANG TW' },
  { label: 'JAHMA', value: 'JAHMA' },
  { label: 'HYB', value: 'HYB' },
  { label: 'GMGR', value: 'GMGR' },
  { label: 'GMD', value: 'GMD' },
  { label: 'FGM', value: 'FGM' },
  { label: 'NM', value: 'NM' },
  { label: 'NB', value: 'NB' },
  { label: 'BEST VALVULAS', value: 'BEST VALVULAS' },
  { label: 'PYSTA', value: 'PYSTA' },
  { label: 'Special', value: 'Special' },
  { label: 'Power oil', value: 'Power oil' },
  { label: 'CARBO', value: 'CARBO' },
  { label: 'Surtex', value: 'Surtex' },
  { label: 'VALVULINA', value: 'VALVULINA' },
  { label: 'PREMIUM FILTERS', value: 'PREMIUM FILTERS' },
  { label: 'IBL', value: 'IBL' },
  { label: 'TEK BOND', value: 'TEK BOND' },
  { label: 'SCHADEK', value: 'SCHADEK' },
  { label: 'USUZU', value: 'USUZU' },
  { label: 'HKT', value: 'HKT' },
  { label: 'TAMA', value: 'TAMA' },
  { label: 'LIDER EPOXI', value: 'LIDER EPOXI' },
  { label: 'Sintesolda', value: 'Sintesolda' },
  { label: 'CELLUX', value: 'CELLUX' },
  { label: 'MACGREY', value: 'MACGREY' },
  { label: 'BROSOL', value: 'BROSOL' },
  { label: 'BRASIL', value: 'BRASIL' },
  { label: 'ARGENTINA', value: 'ARGENTINA' },
  { label: 'NBW', value: 'NBW' },
  { label: 'KBS', value: 'KBS' },
  { label: 'SORES GENUINE PARTS', value: 'SORES GENUINE PARTS' },
  { label: 'EXTREME', value: 'EXTREME' },
  { label: 'OSSCA', value: 'OSSCA' },
  { label: 'KAITEN', value: 'KAITEN' },
  { label: 'Castelautos', value: 'Castelautos' },
];
